# Generated by Django 4.0.5 on 2022-06-15 11:16

import dishes.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('procedure', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('Ingredients', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('video', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/%y', validators=[dishes.validators.file_size])),
                ('nutritional_values', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(default='Local Dish', to='dishes.category')),
                ('type', models.ManyToManyField(default='normal', to='dishes.type')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
