# Generated by Django 4.0.5 on 2022-06-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_fullname_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carts',
            field=models.IntegerField(default=0, verbose_name='carts'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.IntegerField(default=0, verbose_name='notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_dishes',
            field=models.IntegerField(default=0, verbose_name='saved_dishes'),
        ),
    ]
