import Head from "next/head";
import FoodVendor from "../components/Home/FoodVendor";
import Header from "../components/Header";
import Hero from "../components/Home/Hero";
import PopularRecipe from "../components/Home/PopularRecipe";
import Testimonial from "../components/Home/Testimonial";
import Subscribe from "../components/Home/Subscribe";
import Footer from "../components/Footer";
import Layout from "../hoc/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-lightOrange">
        <Layout />
        <Hero />
        <PopularRecipe />
        <FoodVendor />
        <Testimonial />
        <Subscribe />
        <Footer />
      </div>
    </div>
  );
}
