import Head from "next/head";
import Image from "next/image";
import FoodVendor from "../components/Home/FoodVendor";
import Header from "../components/Header";
import Hero from "../components/Home/Hero";
import PopularRecipe from "../components/Home/PopularRecipe";
import styles from "../styles/Home.module.css";
import Testimonial from "../components/Home/Testimonial";
import Subscribe from "../components/Home/Subscribe";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100&display=swap" rel="stylesheet" />
      </Head>
      <div className="bg-lightOrange">
        <Header />
        <Hero />
        <PopularRecipe />
        <FoodVendor />
        <Testimonial />
        <Subscribe />
        <Footer />
      </div>
    </div>
  );
}
